-- Project:   rms-server
-- File:      runonce-prepare-db-mysql-ddl.sql
-- License: 
--            This file is licensed under GNU General Public License version 3
--            http://www.gnu.org/licenses/gpl-3.0.txt
--
-- Copyright: Bartosz Cichecki [ cichecki.bartosz@gmail.com ]
-- Date:      09-12-2012

-- AUTOGENERATED

USE `rms`;

-- MySQL dump 10.13  Distrib 5.5.28, for Win64 (x86)
--
-- Host: localhost    Database: rms
-- ------------------------------------------------------
-- Server version	5.5.28-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `access_history`
--

DROP TABLE IF EXISTS `access_history`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `access_history` (
  `ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) NOT NULL,
  `ACCESS_DATE` datetime NOT NULL,
  `AUTHENTICATION_STATUS` varchar(255) NOT NULL,
  `USER_IP` varchar(255) DEFAULT NULL,
  `USERNAME` varchar(255) DEFAULT NULL,
  `CREATED_BY_ID` varchar(255) DEFAULT NULL,
  `MODIFIED_BY_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `access_history`
--

LOCK TABLES `access_history` WRITE;
/*!40000 ALTER TABLE `access_history` DISABLE KEYS */;
/*!40000 ALTER TABLE `access_history` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `address_data`
--

DROP TABLE IF EXISTS `address_data`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `address_data` (
  `ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) NOT NULL,
  `BIRTHDAY` datetime DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,
  `COUNTRY` varchar(50) DEFAULT NULL,
  `FIRST_NAME` varchar(250) DEFAULT NULL,
  `HOUSE_NUMBER` varchar(10) DEFAULT NULL,
  `LAST_NAME` varchar(250) DEFAULT NULL,
  `MIDDLE_NAME` varchar(250) DEFAULT NULL,
  `STREET` varchar(250) DEFAULT NULL,
  `STREET_NUMBER` varchar(10) DEFAULT NULL,
  `TITLE` varchar(250) DEFAULT NULL,
  `ZIP_CODE` varchar(10) DEFAULT NULL,
  `CREATED_BY_ID` varchar(255) DEFAULT NULL,
  `MODIFIED_BY_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `address_data`
--

LOCK TABLES `address_data` WRITE;
/*!40000 ALTER TABLE `address_data` DISABLE KEYS */;
/*!40000 ALTER TABLE `address_data` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `address_data_contacts`
--

DROP TABLE IF EXISTS `address_data_contacts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `address_data_contacts` (
  `ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) NOT NULL,
  `TYPE` varchar(255) NOT NULL,
  `VALUE` varchar(250) NOT NULL,
  `CREATED_BY_ID` varchar(255) DEFAULT NULL,
  `MODIFIED_BY_ID` varchar(255) DEFAULT NULL,
  `ADDRESS_DATA` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `FK6826501D44184EBA` (`ADDRESS_DATA`),
  CONSTRAINT `FK6826501D44184EBA` FOREIGN KEY (`ADDRESS_DATA`) REFERENCES `address_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `address_data_contacts`
--

LOCK TABLES `address_data_contacts` WRITE;
/*!40000 ALTER TABLE `address_data_contacts` DISABLE KEYS */;
/*!40000 ALTER TABLE `address_data_contacts` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `c3p0_test_table`
--

DROP TABLE IF EXISTS `c3p0_test_table`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `c3p0_test_table` (
  `a` char(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `c3p0_test_table`
--

LOCK TABLES `c3p0_test_table` WRITE;
/*!40000 ALTER TABLE `c3p0_test_table` DISABLE KEYS */;
/*!40000 ALTER TABLE `c3p0_test_table` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `devices`
--

DROP TABLE IF EXISTS `devices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `devices` (
  `ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) NOT NULL,
  `DELETED` tinyint(1) NOT NULL,
  `DESCRIPTION` longtext,
  `NAME` varchar(250) NOT NULL,
  `CREATED_BY_ID` varchar(255) DEFAULT NULL,
  `MODIFIED_BY_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `devices`
--

LOCK TABLES `devices` WRITE;
/*!40000 ALTER TABLE `devices` DISABLE KEYS */;
/*!40000 ALTER TABLE `devices` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `events`
--

DROP TABLE IF EXISTS `events`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `events` (
  `ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) NOT NULL,
  `ARCHIVED` tinyint(1) NOT NULL,
  `DELETED` tinyint(1) NOT NULL,
  `DESCRIPTION` longtext,
  `END_DATE` datetime NOT NULL,
  `LOCKED` tinyint(1) NOT NULL,
  `START_DATE` datetime NOT NULL,
  `TITLE` varchar(250) NOT NULL,
  `TYPE` varchar(255) NOT NULL,
  `CREATED_BY_ID` varchar(255) DEFAULT NULL,
  `MODIFIED_BY_ID` varchar(255) DEFAULT NULL,
  `ADDRESS` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `ADDRESS` (`ADDRESS`),
  KEY `FK7A9AD519EFF68599` (`ADDRESS`),
  CONSTRAINT `FK7A9AD519EFF68599` FOREIGN KEY (`ADDRESS`) REFERENCES `address_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `events`
--

LOCK TABLES `events` WRITE;
/*!40000 ALTER TABLE `events` DISABLE KEYS */;
/*!40000 ALTER TABLE `events` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `events_devices_link`
--

DROP TABLE IF EXISTS `events_devices_link`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `events_devices_link` (
  `EVENT_ID` varchar(255) NOT NULL,
  `DEVICE_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`EVENT_ID`,`DEVICE_ID`),
  KEY `FKB3B07BA2202EBD61` (`EVENT_ID`),
  KEY `FKB3B07BA2BE7B1899` (`DEVICE_ID`),
  CONSTRAINT `FKB3B07BA2BE7B1899` FOREIGN KEY (`DEVICE_ID`) REFERENCES `devices` (`ID`),
  CONSTRAINT `FKB3B07BA2202EBD61` FOREIGN KEY (`EVENT_ID`) REFERENCES `events` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `events_devices_link`
--

LOCK TABLES `events_devices_link` WRITE;
/*!40000 ALTER TABLE `events_devices_link` DISABLE KEYS */;
/*!40000 ALTER TABLE `events_devices_link` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `events_users_link`
--

DROP TABLE IF EXISTS `events_users_link`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `events_users_link` (
  `EVENT_ID` varchar(255) NOT NULL,
  `USER_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`EVENT_ID`,`USER_ID`),
  KEY `FK43F8C2D7202EBD61` (`EVENT_ID`),
  KEY `FK43F8C2D7473F93B9` (`USER_ID`),
  CONSTRAINT `FK43F8C2D7473F93B9` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`),
  CONSTRAINT `FK43F8C2D7202EBD61` FOREIGN KEY (`EVENT_ID`) REFERENCES `events` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `events_users_link`
--

LOCK TABLES `events_users_link` WRITE;
/*!40000 ALTER TABLE `events_users_link` DISABLE KEYS */;
/*!40000 ALTER TABLE `events_users_link` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `message_recipents`
--

DROP TABLE IF EXISTS `message_recipents`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `message_recipents` (
  `ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) NOT NULL,
  `ARCHIVED_BY_RECIPENT` tinyint(1) NOT NULL,
  `DELETED_BY_RECIPENT` tinyint(1) NOT NULL,
  `READ_DATE` datetime DEFAULT NULL,
  `CREATED_BY_ID` varchar(255) DEFAULT NULL,
  `MODIFIED_BY_ID` varchar(255) DEFAULT NULL,
  `RECIPENT` varchar(255) NOT NULL,
  `MESSAGE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `FKBDDAE4A747C43B35` (`MESSAGE`),
  KEY `FKBDDAE4A7200BDD7E` (`RECIPENT`),
  CONSTRAINT `FKBDDAE4A7200BDD7E` FOREIGN KEY (`RECIPENT`) REFERENCES `users` (`ID`),
  CONSTRAINT `FKBDDAE4A747C43B35` FOREIGN KEY (`MESSAGE`) REFERENCES `messages` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `message_recipents`
--

LOCK TABLES `message_recipents` WRITE;
/*!40000 ALTER TABLE `message_recipents` DISABLE KEYS */;
/*!40000 ALTER TABLE `message_recipents` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `messages`
--

DROP TABLE IF EXISTS `messages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `messages` (
  `ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) NOT NULL,
  `ARCHIVED_BY_SENDER` tinyint(1) NOT NULL,
  `CONTENT` longtext NOT NULL,
  `DATE_SENT` datetime NOT NULL,
  `DELETED_BY_SENDER` tinyint(1) NOT NULL,
  `SUBJECT` varchar(250) NOT NULL,
  `CREATED_BY_ID` varchar(255) DEFAULT NULL,
  `MODIFIED_BY_ID` varchar(255) DEFAULT NULL,
  `SENDER` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  KEY `FK131AF14C1A04BFDF` (`SENDER`),
  CONSTRAINT `FK131AF14C1A04BFDF` FOREIGN KEY (`SENDER`) REFERENCES `users` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `messages`
--

LOCK TABLES `messages` WRITE;
/*!40000 ALTER TABLE `messages` DISABLE KEYS */;
/*!40000 ALTER TABLE `messages` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `privileges`
--

DROP TABLE IF EXISTS `privileges`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `privileges` (
  `ROLE_ID` varchar(255) NOT NULL,
  `PRIVILEGE` varchar(255) NOT NULL,
  PRIMARY KEY (`ROLE_ID`,`PRIVILEGE`),
  KEY `FKBA4DCBE29B9F6399` (`ROLE_ID`),
  CONSTRAINT `FKBA4DCBE29B9F6399` FOREIGN KEY (`ROLE_ID`) REFERENCES `roles` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `privileges`
--

LOCK TABLES `privileges` WRITE;
/*!40000 ALTER TABLE `privileges` DISABLE KEYS */;
/*!40000 ALTER TABLE `privileges` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `roles`
--

DROP TABLE IF EXISTS `roles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `roles` (
  `ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `CREATED_BY_ID` varchar(255) DEFAULT NULL,
  `MODIFIED_BY_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `NAME` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `roles`
--

LOCK TABLES `roles` WRITE;
/*!40000 ALTER TABLE `roles` DISABLE KEYS */;
/*!40000 ALTER TABLE `roles` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `users` (
  `ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `MODIFICATION_DATE` datetime DEFAULT NULL,
  `VERSION` bigint(20) NOT NULL,
  `COMMENT` longtext,
  `DELETED` tinyint(1) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `LOCKED` tinyint(1) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `USERNAME` varchar(32) NOT NULL,
  `CREATED_BY_ID` varchar(255) DEFAULT NULL,
  `MODIFIED_BY_ID` varchar(255) DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `ROLE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`),
  UNIQUE KEY `USERNAME` (`USERNAME`),
  UNIQUE KEY `ADDRESS` (`ADDRESS`),
  KEY `FK4D495E8EFF68599` (`ADDRESS`),
  KEY `FK4D495E849C34E8B` (`ROLE`),
  CONSTRAINT `FK4D495E849C34E8B` FOREIGN KEY (`ROLE`) REFERENCES `roles` (`ID`),
  CONSTRAINT `FK4D495E8EFF68599` FOREIGN KEY (`ADDRESS`) REFERENCES `address_data` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `users`
--

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2012-12-09 23:10:36
